carapace-sh/carapace-bin

completers/git_completer/cmd/restore.go

added git restore

---

completers/git_completer/cmd/action/action.go
completers/git_completer/cmd/stash.go
completers/git_completer/cmd/stash_branch.go
completers/git_completer/cmd/stash_clear.go
completers/git_completer/cmd/stash_drop.go
completers/git_completer/cmd/stash_list.go
completers/git_completer/cmd/stash_pop.go
completers/git_completer/cmd/stash_push.go
completers/git_completer/cmd/stash_show.go

added git stash

---

completers/git_completer/cmd/rebase.go

added git rebase

---

cmd/carapace/cmd/lazyInit.go
docker-compose.yml
go.mod
go.sum

From [0.17](https://elv.sh/blog/0.17.0-release-notes.html), lambda syntax on the form `[args...]{...}` are deprecated. The form `{|args...| ...}` should be use instead.

Edit elvish lazy for 0.17 depreciation correction

---

completers/java_completer/cmd/action/classes.go
completers/java_completer/cmd/root.go

- complete filenames without `.class` suffix (assume these are named
correctly)
- only complete these if neither classpath flag nor env is set
- support classpath env for classpath classes completion
fix #962

java: fix positional completion

---

cmd/carapace/cmd/lazyInit.go

[Some time ago](https://github.com/xonsh/xonsh/commit/38295a1dd941451362d2e3d14dd29d94ba4f54ce#diff-760c3694d0d42857a53eed69fd473281744aadcca5830837c95e2c17b9665128), Xonsh stopped exporting the `builtins` module from `xonsh.completers.tools` used by [`xonsh_lazy`](https://github.com/rsteube/carapace-bin/blob/a16b67e1b0c03e47915530e1643985a7e449fb4c/cmd/carapace/cmd/lazyInit.go#L266) to access `__xonsh__.completers`. Until recently it didn't seem to be an issue (although I couldn't figure out why), but of late, trying to use carapace as a Xonsh completer leads to `NameError: name 'builtins' is not defined`.
This patch should fix the issue, by using `xonsh.built_ins.XSH` instead, which seems to be the new standard throughout Xonsh's codebase.

Replace deprecated `builtins.__xonsh__` by `xonsh.built_ins.XSH`

---

completers/git_completer/cmd/push.go
completers/git_completer/cmd/root.go
go.mod
go.sum
pkg/actions/tools/git/alias.go

This adds support for git aliases, both autocompleting the alias and any parameters for the alias itself. For example, given an alias `alias.po = push origin`
`git p<TAB>` will suggest `po` and `git po <TAB>` will suggest branches that can be pushed to origin.

git: add support for aliases

---

go.mod
go.sum

revert to cornfeedhobo/pflag for patch release

---

completers/sudo_completer/cmd/root.go
pkg/actions/bridge/carapace.go

- specs override embedded completers with the same name
fix #1306

ActionCarapaceBin: support spec completion

---

completers/pulumi_completer/cmd/stack_select.go

`pulumi stack rm` already accepted a stack. I did the same for `pulumi stack select`

`pulumi stack select` accepts a stack as a positional arg

---

completers/pulumi_completer/cmd/action/urn.go

Use `pulumi stack export` instead of `pulumi stack --show-urns` to get the resources' urns. The former outputs a `json`, whereas the latter outputs a table (maybe more user friendly?).
I think there was an additional `carapace.ActionCallback(...)` call as well. Or was it intentional? The current implementation does not work for me; it completes with the single entry `urn`.

Fix pulumi's resources urns completion

---

cmd/carapace/cmd/root.go
docs/src/spec/user.md
go.mod
go.sum

`~/.config/carapace/schema.json` is updated whenever the modification
date differs from the carapace binary

spec: keep local schema up to date

---

cmd/generate/gen.go

Using a \ or " inside the action comment breaks the generated code. You would get an error like
```
syntax error: unexpected paths in composite literal; possibly missing comma or }
```

generate: properly escape macro descriptions

---

completers/nix-build_completer/cmd/root.go
completers/nix-build_completer/main.go
completers/nix-channel_completer/cmd/root.go
pkg/actions/tools/nix/attribute.go
pkg/actions/tools/nix/attributeComplete.nix
pkg/actions/tools/nix/channel.go
pkg/actions/tools/nix/path.go

This adds support for `nix-build`. The primary completion here is for attrs with the `-A` parameter and positional completion for a "source". This is based on the code from https://github.com/spwhitt/nix-zsh-completions
This works with the notable exception of not supporting `--arg` and `--argstr`. Those flags take two arguments, one for key and one for value and it seems carapace doesn't support this at all. I looked at other commands and it seems for similar commands they just treat them as string or boolean flags and leave the arguments to be positional but we actually need to get the values to do the completion.
A simple way to test the attr completion is
```
nix-build '<nixpkgs>' -A he<TAB>
```

nix-build: add initial support

---

cmd/carapace/cmd/lazyInit.go

- The `completions` subrecord also contains an `external` subrecord.
- `enable_external_completion`, `max_external_completion_results`, and `external_completer` have been moved into the aforementioned subrecord.
https://www.nushell.sh/blog/2022-11-29-nushell-0.72.html

fix: setup changes since nushell 0.72

---

cmd/carapace/cmd/root.go

zsh: fix duplicate output

---

completers/nix-shell_completer/cmd/root.go
completers/nix-shell_completer/main.go

Add support for `nix-shell`. Technically, this sort of kind of also has extra secret parameters from `nix-instantiate` but this should expose the most common options people use.

nix-shell: add initial support

---

.github/workflows/winget.yml

github: added winget publishing

---

completers/pulumi_completer/cmd/stack_graph.go

I noticed this flag was missing. Documentation: https://www.pulumi.com/docs/cli/commands/pulumi_stack_graph/

pulumi: add flag to `pulumi stack graph`

---

cmd/carapace/cmd/lazyInit.go

fixes https://github.com/rsteube/carapace-bin/issues/1761
I did a global search and replace of `let-env ` with `$env.`; hopefully, this catches all instances of `let-env`

[nushell init] replace `let-env var =` with `$env.var =`

---

.github/workflows/go.yml

Winget Releaser now supports non-Windows runners, and `ubuntu-latest` is generally faster.

Change Winget Releaser job to `ubuntu-latest`

---

cmd/carapace-parse/cmd/root.go
docs/src/development/creatingCompleters.md

It would still be great if it would be documented how to install carapace-parse on you system

Reflect the rename from caraparse to carapace-parse

---

completers/zoxide_completer/cmd/add.go
completers/zoxide_completer/cmd/edit.go
completers/zoxide_completer/cmd/import.go
completers/zoxide_completer/cmd/init.go
completers/zoxide_completer/cmd/query.go
completers/zoxide_completer/cmd/remove.go
completers/zoxide_completer/cmd/root.go
completers/zoxide_completer/main.go
pkg/actions/env/zoxide.go
pkg/actions/tools/zoxide/zoxide.go

added zoxide

---

pkg/actions/net/net.go

Completing any SSH command with hosts threw an error if ~/.ssh/config was missing, even if other completion options were available like ~/.ssh/known_hosts. This change silences that error for a cleaner experience.
Before:
```console
$ carapace scp fish scp -J
-J100.126.5.95
-JERR   open /home/malcolm/.ssh/config: no such file or directory
-Jfern
-Jfern.lan
-Jgithub.com
-Jsrv.us
```
After:
```console
$ carapace scp fish scp -J
-J100.126.5.95
-Jfern
-Jfern.lan
-Jgithub.com
-Jsrv.us
```

Silence missing ssh config in net.ActionHosts

---

cmd/carapace/cmd/lazyInit.go

Update nushell snippet to fix minor breakage and align with the developers' suggested configuration.
Currently, commands that rely on PATH are misinterpreted. See example below when `which` is run for any binary.
```
Error: nu::shell::env_var_not_a_string
× 'PATH' is not representable as a string.
╭─[/home/sia/.cache/carapace/init.nu:1:1]
1 │ $env.PATH = ($env.PATH | prepend "/home/sia/.config/carapace/bin")
·             ───────────────────────────┬──────────────────────────
·                                        ╰── value not representable as a string
2 │
╰────
help: The 'PATH' environment variable must be a string or be convertible to a string.
Either make sure 'PATH' is a string, or add a 'to_string' entry for it in ENV_CONVERSIONS
```
The [latest nushell …

Update Nushell Integration

---

docs/src/setup.md

This PR adds a section in the setup doc for enabling case-insensitive argument matching, as documented in #1791. 
This only adds a sentence about setting environment variables, let me know if code samples are required, I can add one that would work with `bash` and `zsh`.

doc: setup - add case-insensitive match section

---

pkg/actions/tools/jj/branch.go

jj: ActionRemotebranches - fix `ahead by x commits`

---

completers/systemctl_completer/cmd/status.go

When completing systemctl status or systemctl --user status we get a competion for every PID on the system. Doesn't seem intuitive if using completion as an "exploration TUI".
------
I hope I'm not stepping on anyones foot here, this is my second time trying carapace out. I've used systemctl to test and have been quite annoyed with carapace listing every PID on the system for completion so I figured I'd remove it, send a PR and maybe get a bit of discussion.
https://rsteube.github.io/carapace-bin/overlay.html didn't make me any wiser as to if I can get rid of this with YAML 😄

Remove PID lookup from systemctl status

---

completers/fastfetch_completer/cmd/root.go
completers/fastfetch_completer/main.go

Thanks for your great project! This PR tries to add support for my project [fastfetch](https://github.com/fastfetch-cli/fastfetch)
Fastfetch supports more than 100 flags, and it's still growing, so I don't want to hard-code these flags, and ends up with parsing its help message. It's actually my first time to write go code and I know the implementation needs more polish. I'm opening this PR to get some advices.

fastfetch: initial commit

---

pkg/actions/tools/git/ref.go

git: ActionRefs - include tilde suffix for `HEAD`

---

pkg/actions/tools/git/commit.go
pkg/actions/tools/git/ref.go

git: ActionHeadCommits - always use `~` style

---

cmd/carapace/cmd/root.go
docs/src/release_notes/v0.29.md
docs/src/spec/user.md

now available at https://carapace.sh/schemas/command.json

carapace: removed schema generation

---

cmd/carapace/cmd/lazyinit/nushell.go

Heho,
updated the current nushell setup, to enable completions on aliases (most of them) as well.
Kind regards
Alexander

nushell: added alias support for completions

---

completers/git_completer/cmd/diff.go

related https://github.com/rsteube/carapace-bin/issues/2115

git: diff - fix refrange

---

completers/git_completer/cmd/diff.go

git: diff - basic filtering

---

completers/git_completer/cmd/diff.go
completers/git_completer/cmd/difftool.go

git: difftool - use diff completion

---

completers/adb_completer/cmd/tcpip.go

the adb completer incorrectly used `tcip` as a completion instead of `tcpip`.
I am not completely familiar with the codebase but from my guess I replaced all instances of `tcip` in 
`completers/adb_completer/cmd/tcip.go` and then renamed the file to `tcpip.go`

adb incorrectly used tcip instead of tcpip

---

go.mod
go.sum

This reverts commit 525f24af7a94c51b451380455b9c9742b4a6aa6f.

Revert "elvish: tag support"

---

completers/brew_completer/cmd/audit.go
pkg/actions/env/homebrew.go

brew: audit

---

completers/git_completer/cmd/push.go

This PR changes to completion of `git push` to suggest local branches instead of remote branches.
To me, the current approach to show remote branches is not useful, because it suggests to push remote branches to remotes. The command `git-push` syntax [per documentation](https://git-scm.com/docs/git-push#Documentation/git-push.txt-ltrefspecgt82308203) is:
> \<refspec>…​
> 
> Specify what destination ref to update with what source object. The format of a <refspec> parameter is an optional plus +, followed by the source object <src>, followed by a colon :, followed by the destination ref <dst>.
So IMO, after the repository argument, `carapace` should suggest local branches, as the refspec starts with the source object.

git: suggest local branches for push

---

completers/kubectl_completer/cmd/apply_editLastApplied.go
completers/kubectl_completer/cmd/apply_viewLastApplied.go
completers/kubectl_completer/cmd/attach.go
completers/kubectl_completer/cmd/auth_canI.go
completers/kubectl_completer/cmd/edit.go
completers/kubectl_completer/cmd/exec.go
completers/kubectl_completer/cmd/logs.go
completers/kubectl_completer/cmd/portForward.go
completers/kubectl_completer/cmd/rollout_history.go
completers/kubectl_completer/cmd/rollout_pause.go
completers/kubectl_completer/cmd/rollout_restart.go
completers/kubectl_completer/cmd/rollout_resume.go
completers/kubectl_completer/cmd/rollout_status.go
completers/kubectl_completer/cmd/rollout_undo.go
completers/kubectl_completer/cmd/set_env.go
pkg/actions/tools/kubectl/api.go

Currently, when trying to autocomplete serveral command, which require an API resource and resource, the namespace flag is not respected.
```bash
kubectl logs -n other-ns pods/
```
shows pods from the current namespace, not `other-ns`.
This PR adds namespace parameter to the `kubectl.ActionApiResourceResources`.

kubectl: respect namespace flag, when completing ApiResourceResources

---

completers/jj_completer/cmd/config_list.go
completers/jj_completer/cmd/diff.go
completers/jj_completer/cmd/git_init.go
completers/jj_completer/cmd/interdiff.go

* added subcommand for `jj git init`
* added --template/-T for `jj config list`
* added --context for `jj diff` and `jj interdiff`
I did not add actions for completing the template language since it seemed out-of-scope for the project (it seems to be a DSL with a much higher complexity level than the revsets grammer, more comparable to awk scripts)

Updated jj completer for jj v0.15.1

---

completers/jj_completer/cmd/branch_list.go
completers/jj_completer/cmd/root.go
completers/jj_completer/cmd/sparse_edit.go
completers/jj_completer/cmd/sparse_reset.go
completers/jj_completer/cmd/sparse_set.go
completers/jj_completer/cmd/split.go
completers/jj_completer/cmd/squash.go

- --from, --into, and --to added to `jj squash`
- `jj sparse set [--edit/--reset]` have been moved to subcommands `jj sparse [edit|reset]`
- --conflicted added to `jj branch list`
- --all renamed --all-remotes for `jj branch list`
- --siblings added to `jj split`
- global `--quiet` flag added

Updated jujutsu completer to jj v0.16.0

---

pkg/actions/tools/git/ref.go

git: ActionRefs - fix nospace for `HEAD~`

---

completers/gh_completer/cmd/action/api.go
completers/gh_completer/cmd/action/gist.go
completers/gh_completer/cmd/action/repository.go
completers/gh_completer/cmd/action/search.go

gh: api - fix fake repo flag

---

completers/jj_completer/cmd/branch_list.go
completers/jj_completer/cmd/fix.go
completers/jj_completer/cmd/git_push.go
completers/jj_completer/cmd/new.go
completers/jj_completer/cmd/tag.go
completers/jj_completer/cmd/tag_help.go
completers/jj_completer/cmd/tag_list.go
pkg/actions/tools/jj/rev.go

- Added ``-T/--template` flags to `jj branch list`
- Added completions for `jj tag`
- `--insert-after` and `--insert-before` on `jj new` now take revisions
- Added `--allow-empty-description` flag to `jj git push`
- Added new revsets `mutable()`, `immutable()`, and `reachable(srcs, domain)`

jj: Updated completions to v0.18.0

---

completers/jj_completer/cmd/branch_move.go
completers/jj_completer/cmd/commit.go
completers/jj_completer/cmd/diff.go
completers/jj_completer/cmd/file.go
completers/jj_completer/cmd/file_chmod.go
completers/jj_completer/cmd/file_help.go
completers/jj_completer/cmd/file_list.go
completers/jj_completer/cmd/file_show.go
completers/jj_completer/cmd/git_remote_add.go
completers/jj_completer/cmd/git_remote_setUrl.go
completers/jj_completer/cmd/log.go
completers/jj_completer/cmd/next.go
completers/jj_completer/cmd/obslog.go
completers/jj_completer/cmd/operation_log.go
completers/jj_completer/cmd/prev.go
completers/jj_completer/cmd/split.go
completers/jj_completer/cmd/squash.go

- `jj split --siblings` deprecated for `--parallelize`
- `jj log`, `jj obslog`, and `jj op log` alias for flag `--limit` changed from `-l` to `-n`
- new `jj file` command to replace deprecated `jj files`, `jj cat`, and `jj chmod`
- new command `jj branch move` added
- new command `jj git remote set-url` added
- new flag `--name-only` added to `jj diff`
- new flag `--conflict` added to `jj next` and `jj prev`
- new flag `--reset-author` added to `jj commit`
- new flag `--keep-emptied` added to `jj squash`
- fixed typo in `jj git remote add` usage string

jj_completer: updated for jj v0.19.0

---

completers/helm_completer/cmd/install.go
completers/helm_completer/cmd/lint.go
completers/helm_completer/cmd/template.go
completers/helm_completer/cmd/upgrade.go

Currently, running `helm install release chart -f <TAB>` doesn't autocomplete override YAML values files. This PR fixes that by completing yaml file paths after the -f (or --values) parameter.

helm: Add support for values files

---

completers/artisan_completer/cmd/complete.go
completers/artisan_completer/cmd/horizonPurge.go
completers/artisan_completer/cmd/serve.go

artisan: complete, horizonpurge, serve

---

completers/just_completer/cmd/root.go
pkg/actions/tools/just/recipe.go
pkg/actions/tools/just/variable.go

just: fix quotes

---

completers/ffmpeg_completer/cmd/root.go
pkg/actions/tools/ffmpeg/bitstreamFilter.go
pkg/actions/tools/ffmpeg/codec.go
pkg/actions/tools/ffmpeg/decoder.go
pkg/actions/tools/ffmpeg/demuxer.go
pkg/actions/tools/ffmpeg/device.go
pkg/actions/tools/ffmpeg/encoder.go
pkg/actions/tools/ffmpeg/format.go
pkg/actions/tools/ffmpeg/help.go
pkg/actions/tools/ffmpeg/hwAcceleration.go
pkg/actions/tools/ffmpeg/loglevel.go
pkg/actions/tools/ffmpeg/muxer.go

Things done in this pr:
- fixes format completion, not returning anything
- filter device type for sink and source
- filter codec type
- on codec completion also fill in encoders and copy
- handle subtitle codec
- autocomplete all codecs if codec is not specified

fixes and improvements to FFmpeg autocompletion

---

completers/jj_completer/cmd/backout.go
completers/jj_completer/cmd/operation_diff.go
completers/jj_completer/cmd/operation_show.go
completers/jj_completer/cmd/rebase.go
pkg/actions/tools/jj/rev.go

- Added `--skip-emptied` flag to `jj rebase`
- Renamed `jj backout --revision` to `jj backout --revisions`
- Added new revset functions
* tracked_remote_branches
* untracked_remote_branches
* diff_contains
* author_date
* committer_date
- Changed description of file revset function
- Added `jj operation show` command
- Added `jj operation diff` command

jj: Updated completer to v0.20.0

---

completers/jj_completer/cmd/file_untrack.go
completers/jj_completer/cmd/next.go
completers/jj_completer/cmd/prev.go

- Renamed `jj untrack` to `jj file untrack`
- Added `--no-edit` flags to `jj next` and `jj prev`

jj_completer: Updated jujutsu completer to version 0.21.0 .

---

pkg/actions/tools/man/page.go

`man -k` command on Mac has slightly different output, for example:
```bash
man -k kube
...
kubeadm-alpha(1), kubeadm alpha(1) - Kubeadm experimental sub-commands
...
```
There are no space before parenthesis, and there may be several results on one line. I modified the regexp to be compatible with this output.

make man macos compatible

---

pkg/actions/tools/git/change.go

git: ActionChanges - evaluate symlinks before generating relative paths

---

completers/bloop_completer/Dockerfile
completers/bloop_completer/cmd/about.go
completers/bloop_completer/cmd/autocomplete.go
completers/bloop_completer/cmd/bsp.go
completers/bloop_completer/cmd/clean.go
completers/bloop_completer/cmd/compile.go
completers/bloop_completer/cmd/configure.go
completers/bloop_completer/cmd/console.go
completers/bloop_completer/cmd/help.go
completers/bloop_completer/cmd/link.go
completers/bloop_completer/cmd/projects.go
completers/bloop_completer/cmd/root.go
completers/bloop_completer/cmd/run.go
completers/bloop_completer/cmd/test.go
completers/bloop_completer/main.go

added bloop

---

completers/bloop_completer/Dockerfile
completers/bloop_completer/cmd/autocomplete.go
completers/bloop_completer/cmd/bsp.go
completers/bloop_completer/cmd/clean.go
completers/bloop_completer/cmd/compile.go
completers/bloop_completer/cmd/console.go
completers/bloop_completer/cmd/link.go
completers/bloop_completer/cmd/root.go
completers/bloop_completer/cmd/run.go
completers/bloop_completer/cmd/test.go
pkg/actions/tools/bloop/bloop.go

bloop: added completions

---

completers/mix_completer/cmd/help.go
completers/mix_completer/cmd/root.go
completers/mix_completer/main.go
pkg/actions/tools/mix/mix.go

Hi there! Saw there was no completer for [mix](https://hexdocs.pm/mix/Mix.html), so I figured I'd take a stab at it. This is my first time writing go so feel free to give any feedback.
There are maybe some other things I could add like listing the `deps` for input into things like `mix deps.update`, but I wasn't totally sure how to so figured I could leave it to someone in the future (since to me those aren't high use commands).

added mix completer

---

completers/jj_completer/cmd/root.go

- Removed completion for now-deprecated persistent flag `--config-toml`
- Added completions for new persistent flags `--config` and `--config-file`

jj_completer: Updated to jujutsu v0.25.0

---

completers/ripsecrets_completer/cmd/root.go
completers/ripsecrets_completer/main.go

There isn't an issue for this so I'll include the info that would go in one here.
This was initially generated with carapace-parse, and then manually edited from there while referencing https://github.com/sirwart/ripsecrets/blob/main/src/args.rs
It's a fairly simple command
ripsecrets
Command-line tool to find secrets in your code and prevent them from being committed
https://github.com/sirwart/ripsecrets

Add ripsecrets completer

---

completers/git_completer/cmd/interpretTrailers.go

There is not much to add, it's all in the title :-)

fix missing s in `git interpret-trailers` command

---

completers/pidof_completer/cmd/root.go
completers/pidof_completer/main.go
completers/pidwait_completer/cmd/root.go
completers/pidwait_completer/main.go
completers/pwait_completer/main.go
completers/pwdx_completer/cmd/root.go
completers/pwdx_completer/main.go
completers/slabtop_completer/cmd/root.go
completers/slabtop_completer/main.go
completers/tload_completer/cmd/root.go
completers/tload_completer/main.go
completers/uptime_completer/cmd/root.go
completers/w_completer/cmd/root.go
completers/watch_completer/cmd/root.go

- Added new completers:
- `pidof`
- `tload`
- `pwdx`
- `slabtop`
- Updated the following to procps-ng 4.0.5:
- `w`
- `uptime`
- `pidwait` (previously `pwait`)
- `watch`

Added pidof, tload, pwdx, slabtop completers; update w, uptime, pidwait, watch to 4.0.5

---

completers/tsh_completer/cmd/kube_login.go
completers/tsh_completer/cmd/proxy_kube.go
pkg/actions/tools/tsh/kube.go

This PR adds support for listing Kubernetes clusters from a Teleport cluster and adds dynamic completion for the `tsh proxy kube` and `tsh kube login` commands.

tsh: improved kube clusters integration

---

completers/cal_completer/cmd/root.go
completers/cal_completer/main.go
completers/chcpu_completer/cmd/root.go
completers/chcpu_completer/main.go
completers/lsblk_completer/cmd/action/action.go
completers/lsblk_completer/cmd/root.go
completers/lscpu_completer/cmd/root.go
completers/lsfd_completer/cmd/action/action.go
completers/lsfd_completer/cmd/root.go
completers/lsfd_completer/main.go
completers/more_completer/cmd/root.go
completers/script_completer/cmd/root.go
completers/script_completer/main.go
completers/scriptlive_completer/cmd/root.go
completers/scriptlive_completer/main.go
completers/scriptreplay_completer/cmd/root.go
completers/scriptreplay_completer/main.go
completers/su_completer/cmd/root.go

- Added new completers:
- `chcpu`
- `cal`
- `script`
- `scriptlive`
- `scriptreplay`
- `lsfd`
- Updated the following to util-linux 2.41:
- `su`
- `lsblk`
- `more`
- `lscpu`

Add/update completers for util-linux 2.41

---

completers/chgrp_completer/cmd/root.go
completers/chmod_completer/cmd/root.go
completers/chown_completer/cmd/root.go
completers/cksum_completer/cmd/root.go
completers/cp_completer/cmd/root.go
completers/cut_completer/cmd/root.go
completers/df_completer/cmd/action/action.go
completers/df_completer/cmd/root.go
completers/factor_completer/cmd/root.go
completers/nproc_completer/cmd/root.go
completers/nproc_completer/main.go
completers/numfmt_completer/cmd/root.go
completers/numfmt_completer/main.go
completers/timeout_completer/cmd/root.go
completers/timeout_completer/main.go

- Added new completers:
- `timeout`
- `nproc`
- `numfmt`
- Updated the following to GNU coreutils 9.7:
- `factor`
- `cp`
- `chgrp`
- `chmod`
- `chown`
- `cksum`
- `cut`
- `df`

Add/update completers for GNU coreutils 9.7

---

pkg/actions/tools/just/recipe.go

This PR adds support for:
- Value-less attributes: Attributes like `[no-cd]`, which are represented as strings and not maps. Previously carapace would just crash if they show up.
- Private recipes: Private recipes are now hidden from completion.
- Modules: Support for completing recipes within imported [modules](https://just.systems/man/en/modules1190.html).

just: add support for private recipes and modules

---

cmd/carapace/cmd/lazyinit/nushell.go

This is a preemptive PR to account for a breaking change which will be part of the next Nushell version, following the merge of https://github.com/nushell/nushell/pull/15654. The change will be part of the v0.105.0 release, which will be on June 10th. This shouldn't be merged until then (or perhaps it could be merged early if carapace will have a release right before June 10th).
The default command now runs closures in order to support lazy evaluation, so to return a closure with `default` you must put the closure in the closure now. I've updated the Nushell init file to account for this.

Update Nushell init script for v0.105.0

---

completers/common/git_completer/cmd/stash_push.go

Introduced in Git 2.35
https://redirect.github.com/git/git/blob/v2.35.0/Documentation/RelNotes/2.35.0.txt#L31-L32
This seems to be the only missing flag from `git stash push` when comparing with the [docs](https://git-scm.com/docs/git-stash#Documentation/git-stash.txt-push-p--patch-S--staged-k--no-keep-index-u--include-untracked-a--all-q--quiet-m--messageltmessagegt--pathspec-from-fileltfilegt--pathspec-file-nul--ltpathspecgt82308203).

ft(git-stash): Add push --staged|-S flag

---

completers/common/jj_completer/cmd/restore.go
pkg/actions/tools/jj/diff.go

Fixes #2824
Default flags were not handled correctly and --to wasn't used to get completions when used.

jj: fix revision flag logic for restore

---

completers/common/xh_completer/cmd/root.go
completers/common/xh_completer/main.go

Closes https://github.com/carapace-sh/carapace-bin/issues/2810
List of flags: https://github.com/ducaale/xh#usage
Is there a way to mark flags as dependencies of others?
e.g. according to the usage docs `--continue` should only be used if `--download` and `--output` are specified

Add `xh` completer

---

completers/common/fileicon_completer/cmd/get.go
completers/common/fileicon_completer/cmd/rm.go
completers/common/fileicon_completer/cmd/root.go
completers/common/fileicon_completer/cmd/set.go
completers/common/fileicon_completer/cmd/test.go
completers/common/fileicon_completer/main.go

Adds completions for https://github.com/mklement0/fileicon, a small utility for managing file/folder icons on mac os

add fileicon completer

---

completers/ramalama_completer/cmd/root.go
completers/ramalama_completer/main.go

Add completer for https://ramalama.ai.
This tool uses `argcomplete` as seen from its included [bash-completion](https://github.com/containers/ramalama/blob/83a75f16f745f9c0d67664c4e8e1a780e3634caa/completions/bash-completion/completions/ramalama).

add ramalama completer

---

completers/common/pass_completer/cmd/root.go

fix(pass-otp): ~/.nix-profile does not have `/usr` prefix/suffix

---

cmd/carapace/cmd/lazyinit/nushell.go

In Nushell version 0.106.0, the `get --ignore-errors` option was renamed to `get --optional`. This PR changes the usage of `get -i` to direct optional cell path accesses. This should ensure that the carapace integration works both before and after Nushell version 0.106.0.
Furthermore, this tweaks the fix from #2796 to be compatible before v0.105.0 as well. It's a bit of an inelegant workaround, but it gets the job done.
Both of these tweaks works on v0.106.0, and also work at least as far back as 0.94.0 which is the oldest version I have on hand to test with.
Sorry to have another change to the Nushell integration script so soon!
Fixes #2876

Make Nushell init script backwards and forwards compatible for v0.106.0

---

cmd/carapace/cmd/lazyinit/cmd.go

- Fix broken CARAPACE_COMPLINE environment variable setting with os.setenv()
- Replace io.popen() with io.popenyield() for async performance
- Add proper pclose handling with file:close() fallback  
- Implement error handling for command execution failures
- Add explicit appendchar fallback (matches[4] or '')
- Use single argmatcher with priority 50 for both variants

Fix and modernize Clink completion implementation
