cmd/completers.go
completers/cksum_completer/cmd/root.go
completers/cksum_completer/main.go

added cksum

---

cmd/completers.go
completers/comm_completer/cmd/root.go
completers/comm_completer/main.go

added comm

---

completers/chown_completer/cmd/root.go

added `--from` completion
related #6

fixed chown

---

completers/chmod_completer/cmd/root.go

MODE not yet completed
related #6

fixed chmod

---

cmd/completers.go
completers/dircolors_completer/cmd/root.go
completers/dircolors_completer/main.go

added dircolors

---

cmd/completers.go
completers/install_completer/cmd/root.go
completers/install_completer/main.go

added install

---

completers/mkdir_completer/cmd/root.go

fixed mkdir

---

cmd/completers.go
completers/mkfifo_completer/cmd/root.go
completers/mkfifo_completer/main.go

added mkfifo

---

cmd/completers.go
completers/mknod_completer/cmd/root.go
completers/mknod_completer/main.go

added mknod

---

cmd/completers.go
completers/rmdir_completer/cmd/t.txt
completers/shred_completer/cmd/root.go
completers/shred_completer/main.go

added shred

---

cmd/completers.go
completers/sync_completer/cmd/root.go
completers/sync_completer/main.go

added sync

---

completers/touch_completer/cmd/root.go

fixed touch

---

cmd/completers.go
completers/vdir_completer/cmd/root.go
completers/vdir_completer/main.go

added vdir

---

cmd/completers.go
completers/csplit_completer/cmd/root.go
completers/csplit_completer/main.go

added csplit

---

cmd/completers.go
completers/fold_completer/cmd/root.go
completers/fold_completer/main.go

added fold

---

cmd/completers.go
completers/head_completer/cmd/root.go
completers/head_completer/main.go

added head

---

cmd/completers.go
completers/join_completer/cmd/root.go
completers/join_completer/main.go

added join

---

cmd/completers.go
completers/md5sum_completer/cmd/root.go
completers/md5sum_completer/main.go

added md5sum

---

cmd/completers.go
completers/paste_completer/cmd/root.go
completers/paste_completer/main.go

added paste

---

cmd/completers.go
completers/split_completer/cmd/root.go
completers/split_completer/main.go

added split

---

cmd/completers.go
completers/tail_completer/cmd/root.go
completers/tail_completer/main.go

added tail

---

cmd/completers.go
completers/tsort_completer/cmd/root.go
completers/tsort_completer/main.go

added tsort

---

cmd/completers.go
completers/unexpand_completer/cmd/root.go
completers/unexpand_completer/main.go

added unexpand

---

cmd/completers.go
completers/uniq_completer/cmd/root.go
completers/uniq_completer/main.go

added uniq

---

cmd/completers.go
completers/basename_completer/cmd/root.go
completers/basename_completer/main.go

added basename

---

cmd/completers.go
completers/chown_completer/cmd/root.go
completers/chroot_completer/cmd/root.go
completers/chroot_completer/main.go
go.mod
go.sum

moved ActionUserGroup() to carapace (updated chown)
#6

added chroot

---

Dockerfile
cmd/completers.go
completers/date_completer/cmd/root.go
completers/date_completer/main.go

added date

---

cmd/completers.go
completers/dirname_completer/cmd/root.go
completers/dirname_completer/main.go

added dirname

---

cmd/completers.go
completers/expr_completer/cmd/root.go
completers/expr_completer/main.go
completers/factor_completer/cmd/root.go
completers/factor_completer/main.go
completers/hostid_completer/cmd/root.go
completers/hostid_completer/main.go

added expr factor and hostid

---

cmd/completers.go
completers/link_completer/cmd/root.go
completers/link_completer/main.go

added link

---

cmd/completers.go
completers/logname_completer/cmd/root.go
completers/logname_completer/main.go
completers/nice_completer/cmd/root.go
completers/nice_completer/main.go
completers/nohup_completer/cmd/root.go
completers/nohup_completer/main.go

added logname nice and nohup

---

cmd/completers.go
completers/pathchk_completer/cmd/root.go
completers/pathchk_completer/main.go
completers/pinky_completer/cmd/root.go
completers/pinky_completer/main.go

added pathchk and pinky

---

cmd/completers.go
completers/env_completer/cmd/root.go
completers/printenv_completer/cmd/root.go
completers/printenv_completer/main.go

added printenv

---

cmd/completers.go
completers/readlink_completer/cmd/root.go
completers/readlink_completer/main.go

added readlink

---

cmd/completers.go
completers/seq_completer/cmd/root.go
completers/seq_completer/main.go
completers/sleep_completer/cmd/root.go
completers/sleep_completer/main.go
completers/stat_completer/cmd/root.go
completers/stat_completer/main.go

added seq sleep and stat

---

cmd/completers.go
completers/tty_completer/cmd/root.go
completers/tty_completer/main.go
completers/uname_completer/cmd/root.go
completers/uname_completer/main.go
completers/unlink_completer/cmd/root.go
completers/unlink_completer/main.go
completers/users_completer/cmd/root.go
completers/users_completer/main.go

added tty uname unlink users

---

cmd/completers.go
completers/who_completer/cmd/root.go
completers/who_completer/main.go
completers/whoami_completer/cmd/root.go
completers/whoami_completer/main.go
completers/yes_completer/cmd/root.go
completers/yes_completer/main.go

added who whoami and yes

---

carapace/cmd/completers.go
completers/grep_completer/cmd/root.go
completers/grep_completer/main.go
completers/sed_completer/cmd/root.go

- removed character in sed_completer (currently causes error in zsh)

added grep

---

carapace/cmd/completers.go
completers/rg_completer/cmd/root.go
completers/rg_completer/cmd/tg.txt
completers/rg_completer/main.go

- some completions missing
- descriptions are a mess

added rg (initial version)

---

carapace/cmd/completers.go
completers/docker_completer/cmd/builder.go
completers/docker_completer/cmd/builder_build.go
completers/docker_completer/cmd/builder_prune.go
completers/docker_completer/cmd/root.go
completers/docker_completer/main.go

- builder build
- builder prune
#96

added docker (incomplete)

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/config.go
completers/docker_completer/cmd/config_create.go
completers/docker_completer/cmd/config_inspect.go
completers/docker_completer/cmd/config_ls.go
completers/docker_completer/cmd/config_rm.go

added config subcommand to docker

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/container.go
completers/docker_completer/cmd/container_attach.go
completers/docker_completer/cmd/container_commit.go
completers/docker_completer/cmd/container_cp.go
completers/docker_completer/cmd/container_create.go
completers/docker_completer/cmd/container_diff.go
completers/docker_completer/cmd/container_exec.go
completers/docker_completer/cmd/container_export.go
completers/docker_completer/cmd/container_inspect.go
completers/docker_completer/cmd/container_kill.go
completers/docker_completer/cmd/container_logs.go
completers/docker_completer/cmd/container_ls.go
completers/docker_completer/cmd/container_pause.go
completers/docker_completer/cmd/container_port.go
completers/docker_completer/cmd/container_prune.go
completers/docker_completer/cmd/container_rename.go
completers/docker_completer/cmd/container_restart.go
completers/docker_completer/cmd/container_rm.go
completers/docker_completer/cmd/container_run.go
completers/docker_completer/cmd/container_start.go
completers/docker_completer/cmd/container_stats.go
completers/docker_completer/cmd/container_stop.go
completers/docker_completer/cmd/container_top.go
completers/docker_completer/cmd/container_unpause.go
completers/docker_completer/cmd/container_update.go
completers/docker_completer/cmd/container_wait.go

added docker container subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/context.go
completers/docker_completer/cmd/context_create.go
completers/docker_completer/cmd/context_export.go
completers/docker_completer/cmd/context_import.go
completers/docker_completer/cmd/context_inspect.go
completers/docker_completer/cmd/context_ls.go
completers/docker_completer/cmd/context_rm.go
completers/docker_completer/cmd/context_update.go
completers/docker_completer/cmd/context_use.go

added docker context subcommand

---

completers/docker_completer/cmd/engine.go
completers/docker_completer/cmd/engine_activate.go
completers/docker_completer/cmd/engine_check.go
completers/docker_completer/cmd/engine_update.go

addedd docker engine subcommand

---

completers/docker_completer/cmd/image.go
completers/docker_completer/cmd/image_build.go
completers/docker_completer/cmd/image_history.go
completers/docker_completer/cmd/image_import.go
completers/docker_completer/cmd/image_inspect.go
completers/docker_completer/cmd/image_load.go
completers/docker_completer/cmd/image_ls.go
completers/docker_completer/cmd/image_prune.go
completers/docker_completer/cmd/image_pull.go
completers/docker_completer/cmd/image_push.go
completers/docker_completer/cmd/image_rm.go
completers/docker_completer/cmd/image_save.go
completers/docker_completer/cmd/image_tag.go

added docker image subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/network.go
completers/docker_completer/cmd/network_connect.go
completers/docker_completer/cmd/network_create.go
completers/docker_completer/cmd/network_disconnect.go
completers/docker_completer/cmd/network_inspect.go
completers/docker_completer/cmd/network_ls.go
completers/docker_completer/cmd/network_prune.go
completers/docker_completer/cmd/network_rm.go

added docker network subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/node.go
completers/docker_completer/cmd/node_demote.go
completers/docker_completer/cmd/node_inspect.go
completers/docker_completer/cmd/node_ls.go
completers/docker_completer/cmd/node_promote.go
completers/docker_completer/cmd/node_ps.go
completers/docker_completer/cmd/node_rm.go
completers/docker_completer/cmd/node_update.go

added docker node subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/plugin.go
completers/docker_completer/cmd/plugin_create.go
completers/docker_completer/cmd/plugin_disable.go
completers/docker_completer/cmd/plugin_enable.go
completers/docker_completer/cmd/plugin_inspect.go
completers/docker_completer/cmd/plugin_install.go
completers/docker_completer/cmd/plugin_ls.go
completers/docker_completer/cmd/plugin_push.go
completers/docker_completer/cmd/plugin_rm.go
completers/docker_completer/cmd/plugin_set.go
completers/docker_completer/cmd/plugin_upgrade.go

added docker plugin subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/secret.go
completers/docker_completer/cmd/secret_create.go
completers/docker_completer/cmd/secret_inspect.go
completers/docker_completer/cmd/secret_ls.go
completers/docker_completer/cmd/secret_rm.go

added docker secret subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/service.go
completers/docker_completer/cmd/service_create.go
completers/docker_completer/cmd/service_inspect.go
completers/docker_completer/cmd/service_logs.go
completers/docker_completer/cmd/service_ls.go
completers/docker_completer/cmd/service_ps.go
completers/docker_completer/cmd/service_rm.go
completers/docker_completer/cmd/service_rollback.go
completers/docker_completer/cmd/service_scale.go
completers/docker_completer/cmd/service_update.go

added docker service subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/docker-compose.yml
completers/docker_completer/cmd/docker_stack.go
completers/docker_completer/cmd/stack_deploy.go
completers/docker_completer/cmd/stack_ls.go
completers/docker_completer/cmd/stack_ps.go
completers/docker_completer/cmd/stack_rm.go
completers/docker_completer/cmd/stack_services.go

added docker stack subcommand

---

completers/docker_completer/cmd/swarm.go
completers/docker_completer/cmd/swarm_ca.go
completers/docker_completer/cmd/swarm_init.go
completers/docker_completer/cmd/swarm_join.go
completers/docker_completer/cmd/swarm_leave.go
completers/docker_completer/cmd/swarm_unlock.go
completers/docker_completer/cmd/swarm_unlockkey.go
completers/docker_completer/cmd/swarm_update.go

added docker swarm subcommand

---

completers/docker_completer/cmd/system.go
completers/docker_completer/cmd/system_df.go
completers/docker_completer/cmd/system_events.go
completers/docker_completer/cmd/system_info.go
completers/docker_completer/cmd/system_prune.go

added docker system subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/trust.go
completers/docker_completer/cmd/trust_inspect.go
completers/docker_completer/cmd/trust_key.go
completers/docker_completer/cmd/trust_key_generate.go
completers/docker_completer/cmd/trust_key_load.go
completers/docker_completer/cmd/trust_revoke.go
completers/docker_completer/cmd/trust_sign.go
completers/docker_completer/cmd/trust_signer.go
completers/docker_completer/cmd/trust_signer_add.go
completers/docker_completer/cmd/trust_signer_remove.go

added docker trust subcommand

---

completers/docker_completer/cmd/action/action.go
completers/docker_completer/cmd/docker-compose.yml
completers/docker_completer/cmd/service_inspect.go
completers/docker_completer/cmd/service_logs.go
completers/docker_completer/cmd/service_ps.go
completers/docker_completer/cmd/service_rm.go
completers/docker_completer/cmd/service_rollback.go
completers/docker_completer/cmd/service_scale.go
completers/docker_completer/cmd/service_update.go
completers/docker_completer/cmd/volume.go
completers/docker_completer/cmd/volume_create.go
completers/docker_completer/cmd/volume_inspect.go
completers/docker_completer/cmd/volume_ls.go
completers/docker_completer/cmd/volume_prune.go
completers/docker_completer/cmd/volume_rm.go

added docker volume subcommand

---

completers/docker_completer/cmd/root.go

still missing:
- inspect
- login
- logout
- search

added direct docker subcommands

---

completers/docker_completer/cmd/inspect.go
completers/docker_completer/cmd/login.go
completers/docker_completer/cmd/logout.go
completers/docker_completer/cmd/root.go
completers/docker_completer/cmd/search.go
completers/docker_completer/cmd/version.go

added docker subcommands

---

completers/git_completer/cmd/action/action.go
completers/git_completer/cmd/push.go

added git push

---

carapace/cmd/completers.go
completers/meld_completer/cmd/root.go
completers/meld_completer/main.go
completers/tail_completer/cmd/root.go
go.mod
go.sum

- updated carapace
- fixed tail optarg flag

added meld completer

---

go.sum
pkg/actions/aws/aws.go
pkg/actions/fs/fs.go
pkg/actions/net/net.go
pkg/actions/os/os.go

- added descriptions to completion

added documentation to actions

---

Dockerfile
completers/cura_completer/cmd/root.go
completers/cura_completer/main.go
completers/git_completer/cmd/add.go

- git add: unchanged changes won't be repeated now
- oil: fix let in docker

added cura

---

completers/git_completer/cmd/merge.go

added git merge

---

completers/git_completer/cmd/fetch.go

added git fetch

---

completers/git_completer/cmd/clone.go

added git clone

---

completers/cargo_completer/cmd/action/action.go
completers/cargo_completer/cmd/bench.go
completers/cargo_completer/cmd/build.go
completers/cargo_completer/cmd/check.go
completers/cargo_completer/cmd/clean.go
completers/cargo_completer/cmd/doc.go
completers/cargo_completer/cmd/init.go
completers/cargo_completer/cmd/install.go
completers/cargo_completer/cmd/new.go
completers/cargo_completer/cmd/publish.go
completers/cargo_completer/cmd/root.go
completers/cargo_completer/cmd/run.go
completers/cargo_completer/cmd/search.go
completers/cargo_completer/cmd/test.go
completers/cargo_completer/cmd/uninstall.go
completers/cargo_completer/cmd/update.go
completers/cargo_completer/main.go

added cargo

---

completers/cargo_completer/cmd/check.go

added cargo check

---

completers/cargo_completer/cmd/clean.go
completers/cargo_completer/cmd/doc.go

updated cargo clean and doc

---

completers/cargo_completer/cmd/action/action.go
completers/cargo_completer/cmd/new.go

updated cargo new

---

completers/cargo_completer/cmd/init.go

updated cargo init

---

completers/cargo_completer/cmd/run.go

updated cargo run

---

completers/cargo_completer/cmd/bench.go

updated cargo bench

---

completers/cargo_completer/cmd/search.go
completers/cargo_completer/cmd/update.go

updated cargo search and update

---

completers/cargo_completer/cmd/action/action.go
completers/cargo_completer/cmd/install.go
completers/cargo_completer/cmd/publish.go
completers/cargo_completer/cmd/uninstall.go

updated cargo install publish and uninstall

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/get.go
completers/kubectl_completer/cmd/root.go
completers/kubectl_completer/main.go

added kubectl (initial version)

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/explain.go
completers/kubectl_completer/cmd/get.go

added kubectl explain

---

completers/kubectl_completer/cmd/explain.go
completers/kubectl_completer/cmd/root.go
completers/kubectl_completer/cmd/run.go

added kubectl run

---

completers/git_completer/cmd/describe.go

added git describe

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/create.go
completers/kubectl_completer/cmd/create_clusterrole.go
completers/kubectl_completer/cmd/run.go

kubectl: added create clusterrole

---

completers/kubectl_completer/cmd/create_clusterrolebinding.go

kubectl: added create clusterrolebinding

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/create_clusterrolebinding.go
completers/kubectl_completer/cmd/get.go

kubectl: updated create clusterrolebinding

---

completers/kubectl_completer/cmd/create_configmap.go
completers/kubectl_completer/cmd/create_cronjob.go
completers/kubectl_completer/cmd/create_deployment.go

kubectl: added create configmap, cronjob, dployment

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/create_clusterrolebinding.go
completers/kubectl_completer/cmd/create_job.go
completers/kubectl_completer/cmd/create_namespace.go
completers/kubectl_completer/cmd/create_poddisruptionbudget.go
completers/kubectl_completer/cmd/create_priorityclass.go
completers/kubectl_completer/cmd/create_quota.go
completers/kubectl_completer/cmd/create_role.go
completers/kubectl_completer/cmd/create_rolebinding.go

kubecltl: added more create subcommands

---

completers/kubectl_completer/cmd/create_secret.go
completers/kubectl_completer/cmd/create_secret_dockerRegistry.go
completers/kubectl_completer/cmd/create_secret_generic.go
completers/kubectl_completer/cmd/create_secret_tls.go

kubectl: add create secret

---

completers/kubectl_completer/cmd/create_serviceaccount.go

kubectl: add create serviceaccount

---

completers/kubectl_completer/cmd/create_service.go
completers/kubectl_completer/cmd/create_service_clusterip.go
completers/kubectl_completer/cmd/create_service_externalname.go
completers/kubectl_completer/cmd/create_service_loadbalancer.go
completers/kubectl_completer/cmd/create_service_nodeport.go

kubectl: added create service subcommands

---

completers/kubectl_completer/cmd/expose.go

kubectl: add expose

---

completers/kubectl_completer/cmd/edit.go

kubectl: added edit

---

completers/kubectl_completer/cmd/delete.go

kubectl: added delete

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/edit.go
completers/kubectl_completer/cmd/set.go
completers/kubectl_completer/cmd/set_env.go
completers/kubectl_completer/cmd/set_image.go
completers/kubectl_completer/cmd/set_resources.go
completers/kubectl_completer/cmd/set_selector.go
completers/kubectl_completer/cmd/set_serviceaccount.go
completers/kubectl_completer/cmd/set_subject.go

kubectl: add set

---

completers/kubectl_completer/cmd/rollout.go
completers/kubectl_completer/cmd/rollout_history.go
completers/kubectl_completer/cmd/rollout_pause.go
completers/kubectl_completer/cmd/rollout_restart.go
completers/kubectl_completer/cmd/rollout_resume.go
completers/kubectl_completer/cmd/rollout_status.go
completers/kubectl_completer/cmd/rollout_undo.go

kubectl: added rollout

---

completers/kubectl_completer/cmd/scale.go

kubectl: add scale

---

completers/kubectl_completer/cmd/autoscale.go

kubectl: add autoscale

---

completers/kubectl_completer/cmd/certificate.go
completers/kubectl_completer/cmd/certificate_approve.go
completers/kubectl_completer/cmd/certificate_deny.go
completers/kubectl_completer/cmd/clusterInfo.go
completers/kubectl_completer/cmd/clusterInfo_dump.go
completers/kubectl_completer/cmd/cordon.go
completers/kubectl_completer/cmd/drain.go
completers/kubectl_completer/cmd/taint.go
completers/kubectl_completer/cmd/top.go
completers/kubectl_completer/cmd/top_node.go
completers/kubectl_completer/cmd/top_pod.go
completers/kubectl_completer/cmd/uncordon.go

kubectl: added cluster management commands

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/attach.go
completers/kubectl_completer/cmd/auth.go
completers/kubectl_completer/cmd/auth_canI.go
completers/kubectl_completer/cmd/auth_reconcile.go
completers/kubectl_completer/cmd/cp.go
completers/kubectl_completer/cmd/describe.go
completers/kubectl_completer/cmd/exec.go
completers/kubectl_completer/cmd/logs.go
completers/kubectl_completer/cmd/portForward.go
completers/kubectl_completer/cmd/proxy.go
pkg/actions/net/port.go

kubectl: added troubleshooting commands

---

completers/kubectl_completer/cmd/apply.go
completers/kubectl_completer/cmd/apply_editLastApplied.go
completers/kubectl_completer/cmd/apply_setLastApplied.go
completers/kubectl_completer/cmd/apply_viewLastApplied.go
completers/kubectl_completer/cmd/convert.go
completers/kubectl_completer/cmd/diff.go
completers/kubectl_completer/cmd/kustomize.go
completers/kubectl_completer/cmd/patch.go
completers/kubectl_completer/cmd/replace.go
completers/kubectl_completer/cmd/wait.go

kubectl: added advanced cmds

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/annotate.go
completers/kubectl_completer/cmd/completion.go
completers/kubectl_completer/cmd/label.go

kubectl settings cmds

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/alpha.go
completers/kubectl_completer/cmd/apiResources.go
completers/kubectl_completer/cmd/apiVersions.go
completers/kubectl_completer/cmd/version.go

kubectl: added other commands

---

completers/kubectl_completer/cmd/action/action.go
completers/kubectl_completer/cmd/config.go
completers/kubectl_completer/cmd/config_currentContext.go
completers/kubectl_completer/cmd/config_deleteCluster.go
completers/kubectl_completer/cmd/config_deleteContext.go
completers/kubectl_completer/cmd/config_getClusters.go
completers/kubectl_completer/cmd/config_getContexts.go
completers/kubectl_completer/cmd/config_renameContext.go
completers/kubectl_completer/cmd/config_set.go
completers/kubectl_completer/cmd/config_setCluster.go
completers/kubectl_completer/cmd/config_setContext.go
completers/kubectl_completer/cmd/config_setCredentials.go
completers/kubectl_completer/cmd/config_unset.go
completers/kubectl_completer/cmd/config_useContext.go
completers/kubectl_completer/cmd/config_view.go
completers/kubectl_completer/cmd/plugin.go
completers/kubectl_completer/cmd/plugin_list.go

kubectl: added config and plugin

---

completers/cargo_completer/cmd/fmt.go
completers/cargo_completer/cmd/root.go

cargo: added fmt

---

completers/stty_completer/cmd/root.go
completers/stty_completer/main.go

added stty

---

completers/git_completer/cmd/switch.go

git: added switch

---

go.mod
pkg/carascrape/scrape.go
pkg/carascrape/scrape_test.go

added carascrape

---

completers/minikube_completer/cmd/action/cache.go
completers/minikube_completer/cmd/cache_add.go
completers/minikube_completer/cmd/cache_delete.go

added cache completion

---

completers/minikube_completer/cmd/action/config.go
completers/minikube_completer/cmd/config_defaults.go
completers/minikube_completer/cmd/config_get.go
completers/minikube_completer/cmd/config_set.go
completers/minikube_completer/cmd/config_unset.go
completers/minikube_completer/cmd/config_view.go

minikube: added config completion

---

completers/minikube_completer/cmd/action/image.go
completers/minikube_completer/cmd/dockerEnv.go
completers/minikube_completer/cmd/image_build.go
completers/minikube_completer/cmd/image_load.go
completers/minikube_completer/cmd/image_rm.go

minikube: image completion

---

completers/minikube_completer/cmd/ip.go
completers/minikube_completer/cmd/logs.go
completers/minikube_completer/cmd/mount.go

minikube: added ip, logs, mount completion

---

completers/minikube_completer/cmd/action/namespace.go
completers/minikube_completer/cmd/pause.go

minikube: pause completion

---

completers/minikube_completer/cmd/podmanEnv.go
completers/minikube_completer/cmd/profile_list.go
completers/minikube_completer/cmd/service.go
completers/minikube_completer/cmd/service_list.go
completers/minikube_completer/cmd/ssh.go
completers/minikube_completer/cmd/sshHost.go
completers/minikube_completer/cmd/sshKey.go
completers/minikube_completer/cmd/start.go

minikube: more completions

---

completers/minikube_completer/cmd/status.go
completers/minikube_completer/cmd/stop.go
completers/minikube_completer/cmd/unpause.go
completers/minikube_completer/cmd/version.go

minikube: finish completions

---

completers/git_completer/cmd/am.go
completers/git_completer/cmd/root.go

git: added am

---

completers/glab_completer/cmd/action/group.go
completers/glab_completer/cmd/action/mergeRequest.go

glab: fix group and mergeRequest completions

---

completers/glab_completer/cmd/action/label.go

glab: fix label completion

---

completers/git_completer/cmd/citool.go

git: citool

---

completers/git_completer/cmd/bundle.go
completers/git_completer/cmd/bundle_create.go
completers/git_completer/cmd/bundle_listHeads.go
completers/git_completer/cmd/bundle_unbundle.go
completers/git_completer/cmd/bundle_verify.go
pkg/actions/git/bundle.go

git: added bundle

---

completers/git_completer/cmd/config.go
pkg/actions/git/config.go

git: added config

---

completers/gh_completer/cmd/action/repo_override.go
completers/gh_completer/cmd/browse.go
completers/gh_completer/cmd/issue.go
completers/gh_completer/cmd/pr.go
completers/gh_completer/cmd/release.go
completers/gh_completer/cmd/run.go
completers/gh_completer/cmd/secret.go
completers/gh_completer/cmd/workflow.go

Add remote urls to repo completion to quickly switch between these (related https://github.com/cli/cli/pull/3942)

gh: add remote urls to repo completion

---

completers/rustc_completer/cmd/root.go
completers/youtube-dl_completer/cmd/action/format.go
completers/youtube-dl_completer/cmd/root.go

- fix regex
- added flag completions
- added caching

youtube: fix format regex pattern

---

completers/dart_completer/cmd/analyze.go
completers/dart_completer/cmd/compile.go
completers/dart_completer/cmd/fix.go
completers/dart_completer/cmd/test.go

https://dart.dev/tools/dart-tool

dart: positional completion

---

completers/flutter_completer/cmd/build_fuchsia.go
completers/flutter_completer/cmd/build_linux.go
completers/flutter_completer/cmd/build_windows.go
completers/flutter_completer/cmd/build_winuwp.go
completers/flutter_completer/cmd/build_xcarchive.go

seems documentation differs from actual subcommands: https://github.com/flutter/flutter/issues/80778
added commands as suggested by default bash completion

flutter: build - inconsistent subcommand documentation

---

completers/cfdisk_completer/cmd/root.go
completers/fdisk_completer/cmd/root.go
completers/flutter_completer/cmd/root.go
completers/gh_completer/cmd/pr_checks.go
completers/glab_completer/cmd/action/mergeRequest.go
completers/glab_completer/cmd/action/repoOverride.go
completers/glab_completer/cmd/repo_archive.go
completers/java_completer/cmd/root.go
completers/kill_completer/cmd/root.go
completers/pandoc_completer/cmd/action/format.go
go.mod
go.sum

use `carapace.Batch` for better performance

---

completers/glab_completer/cmd/action/repoOverride.go
completers/glab_completer/cmd/action/sshKey.go
completers/glab_completer/cmd/repo_view.go
completers/glab_completer/cmd/sshKey.go
completers/glab_completer/cmd/sshKey_add.go
completers/glab_completer/cmd/sshKey_get.go
completers/glab_completer/cmd/sshKey_list.go
completers/glab_completer/cmd/variable_list.go

- repo/view
- ssh-key
- variable/list
- added FakeRepo flag override

glab: new commands from 1.19.0

---

completers/ffmpeg_completer/cmd/action/bitstreamFilter.go
completers/ffmpeg_completer/cmd/action/codec.go
completers/ffmpeg_completer/cmd/action/decoder.go
completers/ffmpeg_completer/cmd/action/demuxer.go
completers/ffmpeg_completer/cmd/action/device.go
completers/ffmpeg_completer/cmd/action/encoder.go
completers/ffmpeg_completer/cmd/action/filter.go
completers/ffmpeg_completer/cmd/action/format.go
completers/ffmpeg_completer/cmd/action/help.go
completers/ffmpeg_completer/cmd/action/hwAcceleration.go
completers/ffmpeg_completer/cmd/action/muxer.go
completers/ffmpeg_completer/cmd/action/protocol.go
completers/ffmpeg_completer/cmd/root.go
completers/ffmpeg_completer/main.go

- added ffmpeg
- tmp
- tmp
- tmp
- tmp

add ffmpeg

---

completers/flutter_completer/cmd/root.go

- removed emulator completion from device-id

flutter: device-id differs from emulator

---

completers/aws_completer/cmd/root.go

aws: support binary completer

---

cmd/carapace/cmd/lazyInit.go
go.mod
go.sum

see https://github.com/rsteube/carapace/issues/244

xonsh: use completion context

---

go.mod
go.sum

see https://github.com/rsteube/carapace/issues/371

xonsh: fix quoted value completion

---

completers/cargo_completer/cmd/fix.go
completers/cargo_completer/cmd/uninstall.go

cargo: added fix

---

completers/ng_completer/cmd/action/config.go
completers/ng_completer/cmd/build.go
completers/ng_completer/cmd/deploy.go
completers/ng_completer/cmd/e2e.go
completers/ng_completer/cmd/extractI18n.go
completers/ng_completer/cmd/lint.go
completers/ng_completer/cmd/run.go
completers/ng_completer/cmd/serve.go
completers/ng_completer/cmd/test.go

filter named builder configuration

ng: run positional completion

---

completers/gh_completer/cmd/run_cancel.go

- was registered to wrong command

gh: fix run completion

---

completers/waypoint_completer/cmd/action/authMethod.go
completers/waypoint_completer/cmd/authMethod_delete.go
completers/waypoint_completer/cmd/authMethod_inspect.go
completers/waypoint_completer/cmd/login.go

waypoint: auth-method completion

---

completers/waypoint_completer/cmd/action/project.go
completers/waypoint_completer/cmd/root.go

waypoint: project completion

---

completers/waypoint_completer/cmd/action/runner.go
completers/waypoint_completer/cmd/project_apply.go
completers/waypoint_completer/cmd/project_inspect.go
completers/waypoint_completer/cmd/runner_profile_inspect.go

- waypoint: add missing project completion
- waypoint: runner profile completion

waypoint runner profile

---

completers/docker-compose_completer/cmd/root.go
completers/docker_completer/cmd/compose.go

seems docker-compose is integrated as compose subcommand in docker
see https://github.com/docker/compose/issues/8550

docker: add compose subcommand (plugin)

---

completers/docker_completer/cmd/compose.go
go.mod
go.sum

docker: added compose subcommand (experimental)

---

cmd/carapace/cmd/lazyInit.go
cmd/carapace/cmd/root.go
completers/carapace_completer/cmd/root.go
go.mod
go.sum

support bash-ble

---

completers/gh_completer/cmd/alias_list.go
completers/gh_completer/cmd/api.go
completers/gh_completer/cmd/auth.go
completers/gh_completer/cmd/auth_login.go
completers/gh_completer/cmd/codespace.go
completers/gh_completer/cmd/codespace_create.go
completers/gh_completer/cmd/codespace_list.go
completers/gh_completer/cmd/config_list.go
completers/gh_completer/cmd/extension.go
completers/gh_completer/cmd/extension_list.go
completers/gh_completer/cmd/gist_list.go
completers/gh_completer/cmd/gpgKey_list.go
completers/gh_completer/cmd/issue_comment.go
completers/gh_completer/cmd/issue_list.go
completers/gh_completer/cmd/pr_comment.go
completers/gh_completer/cmd/pr_list.go
completers/gh_completer/cmd/release.go
completers/gh_completer/cmd/release_list.go
completers/gh_completer/cmd/repo.go
completers/gh_completer/cmd/repo_deployKey_list.go
completers/gh_completer/cmd/repo_fork.go
completers/gh_completer/cmd/run_list.go
completers/gh_completer/cmd/secret_list.go
completers/gh_completer/cmd/secret_set.go
completers/gh_completer/cmd/sshKey_list.go
completers/gh_completer/cmd/workflow_list.go
pkg/carascrape/scrape.go

gh: updates from 2.5.2

---

completers/java_completer/cmd/root.go

java: positional file completion

---

completers/xargs_completer/cmd/root.go

- include path executables
- complete embedded command
- does not yet work work flags of embedded command

xargs: update positional completion

---

completers/sudo_completer/cmd/root.go

sudo: fix flag completion

---

completers/gh_completer/cmd/action/branch.go
completers/gh_completer/cmd/action/pullrequest.go
completers/gh_completer/cmd/action/release.go
pkg/actions/tools/git/change.go

- gh: branch/tag colors
- git: path colors

git path colors

---

cmd/carapace/cmd/root.go
go.mod
go.sum

- added spec completion
- added spec flag
- updated carapace-spec

update carapace spec

---

completers/tmux_completer/cmd/killWindow.go

tmux: kill-window

---

completers/tmux_completer/cmd/killSession.go

tmux: kill-session

---

cmd/carapace/cmd/lazyInit.go

spec: quote path

---

pkg/actions/tools/golang/funcs.go

- go-carpet: func completion
- go-carped: add missing commit

go carpet func

---

completers/git_completer/cmd/worktree.go
completers/git_completer/cmd/worktree_add.go
completers/git_completer/cmd/worktree_list.go
completers/git_completer/cmd/worktree_lock.go
completers/git_completer/cmd/worktree_move.go
completers/git_completer/cmd/worktree_prune.go
completers/git_completer/cmd/worktree_remove.go
completers/git_completer/cmd/worktree_repair.go
completers/git_completer/cmd/worktree_unlock.go
pkg/actions/tools/git/worktree.go

git: worktree

---

cmd/carapace/cmd/root.go
completers/turbo_completer/cmd/bin.go
completers/turbo_completer/cmd/link.go
completers/turbo_completer/cmd/login.go
completers/turbo_completer/cmd/logout.go
completers/turbo_completer/cmd/prune.go
completers/turbo_completer/cmd/root.go
completers/turbo_completer/cmd/run.go
completers/turbo_completer/cmd/unlink.go
completers/turbo_completer/main.go
pkg/actions/tools/turbo/turbo.go

related https://github.com/vercel/turborepo/issues/913

added turbo

---

completers/turbo_completer/cmd/run.go

turbo: run - basic filter completion

---

completers/deno_completer/cmd/action/action.go
completers/deno_completer/cmd/bench.go
completers/deno_completer/cmd/check.go
completers/deno_completer/cmd/completions.go
completers/deno_completer/cmd/task.go
completers/deno_completer/cmd/uninstall.go
completers/deno_completer/cmd/upgrade.go
completers/deno_completer/cmd/vendor.go

existing commands not yet updated

deno: added new commands from 1.22.2

---

cmd/carapace/cmd/lazyInit.go

nushell: filter builtins

---

docker-compose.yml
go.mod
go.sum

docker: added ble

---

completers/git_completer/cmd/diff.go

git: diff - allow positional file completion

---

completers/npm_completer/cmd/runScript.go

Just aliasing `npm run-script` #462

Add `npm run`

---

completers/cargo-watch_completer/cmd/root.go
completers/cargo-watch_completer/main.go

added cargo-watch

---

README.md
cmd/carapace/cmd/lazyInit.go
cmd/carapace/cmd/root.go
docs/src/setup.md
go.mod
go.sum

related rsteube/carapace#547
related nushell/nushell#6295

nushell: update snippet

---

go.mod
go.sum

updated carapace to v0.23.0

---

docs/src/installation.md

doc: nix installation

---

completers/git-extras_completer/cmd/root.go
completers/git-extras_completer/main.go
completers/git_completer/cmd/root.go
go.mod
go.sum

git: support other commands (plugins)

---

completers/git-alias_completer/cmd/root.go
completers/git-alias_completer/main.go
completers/git_completer/cmd/root.go
pkg/actions/tools/git/alias.go

added git-alias

---

completers/git-abort_completer/cmd/root.go
completers/git-abort_completer/main.go

added git-abort

---

completers/git-standup_completer/cmd/root.go
completers/git-standup_completer/main.go

added git-standup

---

completers/xargs_completer/cmd/root.go

xargs: fix completion

---

completers/cargo_completer/cmd/root.go

cargo: prevent `synching channel updates`

---

completers/git_completer/cmd/root.go

git: PreRun performance improvement

---

docs/asciinema/load.js
docs/src/spec/examples.md
docs/src/style.md

doc: asciicast - reverse list for loop to not be affected by dom change

---

pkg/actions/tools/nix/package.go

nix: added package actions

---

completers/mpv_completer/cmd/root.go
pkg/actions/tools/mpv/filter.go

mpv: added filter completion

---

completers/pacman_completer/cmd/sync.go
pkg/actions/tools/pacman/package.go

pacman: sync - fix package search

---

completers/git-archive-file_completer/cmd/root.go
completers/git-archive-file_completer/main.go
completers/git-authors_completer/cmd/root.go
completers/git-authors_completer/main.go
pkg/actions/ps/ps.go

added git-archive-file and git-authors

---

completers/git-info_completer/cmd/root.go
completers/git-info_completer/main.go

added git-info

---

pkg/actions/bridge/argcomplete.go

ActionArgcomplete: fix partial positional not being completed

---

completers/nix-build_completer/cmd/root.go
go.mod
go.sum

nix-build: support nargs

---

completers/git_completer/cmd/commit.go
completers/git_completer/cmd/tag.go
pkg/actions/tools/git/action.go
pkg/actions/tools/git/branch.go
pkg/actions/tools/git/commit.go
pkg/actions/tools/git/stash.go
pkg/actions/tools/git/tag.go

updated Batch to use separate Actions concurrently

git: complete recent commits across all branches

---

pkg/actions/tools/git/action.go
pkg/actions/tools/git/commit.go
pkg/actions/tools/git/config.go

- skip recent merge commits
- revert to old description

git: fix head commit prefix

---

completers/git_completer/cmd/mktag.go

git: mktag

---

completers/git_completer/cmd/branch.go
completers/git_completer/cmd/diff.go
completers/git_completer/cmd/grep.go
completers/git_completer/cmd/log.go
completers/git_completer/cmd/showBranch.go
completers/git_completer/cmd/tag.go
pkg/actions/tools/git/color.go
pkg/actions/tools/git/diff.go

git: move actions

---

completers/conda-env_completer/cmd/config.go
completers/conda-env_completer/cmd/config_vars.go
completers/conda-env_completer/cmd/config_vars_list.go
completers/conda-env_completer/cmd/config_vars_set.go
completers/conda-env_completer/cmd/config_vars_unset.go
completers/conda-env_completer/cmd/create.go
completers/conda-env_completer/cmd/export.go
completers/conda-env_completer/cmd/list.go
completers/conda-env_completer/cmd/remove.go
completers/conda-env_completer/cmd/root.go
completers/conda-env_completer/cmd/update.go
completers/conda-env_completer/main.go
completers/conda_completer/cmd/root.go
pkg/actions/tools/conda/environment.go

added conda-env

---

completers/git_completer/cmd/checkout.go
pkg/actions/tools/git/change.go

git: checkout - complete files

---

.goreleaser.yml

goreleaser: use zip for windows

---

docs/src/style.md

doc: updated style

---

completers/git_completer/cmd/notes.go
completers/git_completer/cmd/notes_add.go
completers/git_completer/cmd/notes_append.go
completers/git_completer/cmd/notes_copy.go
completers/git_completer/cmd/notes_edit.go
completers/git_completer/cmd/notes_getRef.go
completers/git_completer/cmd/notes_list.go
completers/git_completer/cmd/notes_merge.go
completers/git_completer/cmd/notes_prune.go
completers/git_completer/cmd/notes_remove.go
completers/git_completer/cmd/notes_show.go
pkg/actions/tools/git/action.go
pkg/actions/tools/git/commit.go
pkg/actions/tools/git/note.go
pkg/styles/git.go

git: notes

---

completers/scp_completer/cmd/root.go

scp: added missing flags

---

pkg/actions/bridge/carapace.go

ActionCarapaceBin: fallback to file completion

---

pkg/actions/bridge/fish.go

ActionFish: use custom config for bridge

---

cmd/carapace/cmd/root.go
completers/git_completer/cmd/blame.go
completers/git_completer/cmd/show.go
pkg/actions/tools/git/ls.go

git: blame - complete files of given ref and not local ones

---

completers/nix-build_completer/cmd/root.go
completers/nix-instantiate_completer/cmd/root.go
completers/nix-instantiate_completer/main.go
pkg/actions/tools/nix/attribute.go

Adds support for `nix-instantiate`, this shares quite a bit with `nix-build` with some additional parameters.

Nix instantiate

---

.github/workflows/winget.yml

github: limit winget to amd64

---

cmd/carapace/cmd/lazyInit.go

closes https://github.com/rsteube/carapace-bin/issues/1692

reworked nushell integration

---

cmd/generate/gen.go

generate: fix path on windows

---

internal/actions/net/ssh/ssh.go
pkg/actions/net/net.go
pkg/actions/net/ssh/host.go

ActionHosts: also complete configured ssh hosts

---

README.md
docs/src/installation.md
docs/src/setup.md

documentation: updated nushell integration, changed scoop to extra bucket (#11339 from ScoopInstaller/Extras)

documentation: updated nushell integration, changed scoop to extra

---

go.mod
go.sum

updated carapace to v0.37.2

---

completers/go-tool-covdata_completer/cmd/debugdump.go
completers/go-tool-covdata_completer/cmd/func.go
completers/go-tool-covdata_completer/cmd/intersect.go
completers/go-tool-covdata_completer/cmd/merge.go
completers/go-tool-covdata_completer/cmd/percent.go
completers/go-tool-covdata_completer/cmd/pkglist.go
completers/go-tool-covdata_completer/cmd/subtract.go
completers/go-tool-covdata_completer/cmd/textfmt.go
completers/go-tool-cover_completer/cmd/root.go
go.mod
go.sum

related https://github.com/rsteube/carapace/pull/829

go: fix interspersed

---

completers/paru_completer/cmd/database.go
completers/paru_completer/cmd/deptest.go
completers/paru_completer/cmd/files.go
completers/paru_completer/cmd/getpkgbuild.go
completers/paru_completer/cmd/query.go
completers/paru_completer/cmd/remove.go
completers/paru_completer/cmd/root.go
completers/paru_completer/cmd/show.go
completers/paru_completer/cmd/sync.go
completers/paru_completer/cmd/upgrade.go
completers/paru_completer/main.go

added paru

---

completers/fish_completer/cmd/root.go

- bash: fix positional completion
- fish: complete command

fish command completion

---

.github/workflows/go.yml
go.mod
pkg/actions/tools/git/action.go
pkg/actions/tools/git/change.go
pkg/actions/tools/git/commit.go
pkg/actions/tools/git/diff.go

git: relative refs

---

cmd/carapace/cmd/lazyInit.go

environment support for xonsh

---

completers/terragrunt_completer/cmd/root.go
completers/tofu_completer/cmd/action/resource.go
pkg/actions/env/terragrunt.go

related: https://github.com/gruntwork-io/terragrunt/issues/2690

terragrunt: fallback to tofu when terraform is not on path

---

completers/git_completer/cmd/reset.go
pkg/actions/tools/git/change.go
pkg/actions/tools/git/diff.go

git: fix reset

---

completers/git_completer/cmd/checkout.go
completers/git_completer/cmd/reset.go

git: fix checkout

---

completers/gh_completer/cmd/browse.go

see https://github.com/cli/cli/pull/8141

gh: browse - no relative path for explicitly specified repos

---

cmd/carapace/cmd/lazyInit.go

nushell: fix deprecated def-env

---

completers/git_completer/cmd/repack.go

git: repack

---

completers/git_completer/cmd/checkMailmap.go

git: check-mailmap

---

completers/git_completer/cmd/credential.go

git: credential

---

completers/git_completer/cmd/credentialCache.go

git: credential-cache

---

completers/git_completer/cmd/stripspace.go

git: stripspace

---

completers/git_completer/cmd/mergeOneFile.go

git: merge-one-file

---

completers/git_completer/cmd/bugreport.go

git: bugreport

---

completers/git_completer/cmd/instaweb.go

git: instaweb

---

completers/git_completer/cmd/quiltimport.go

git: quiltimport

---

completers/git_completer/cmd/cvsserver.go

git: cvsserver

---

completers/git_completer/cmd/httpBackend.go

git: http-backend

---

completers/git_completer/cmd/updateServerInfo.go

git: update-server-info

---

completers/jj_completer/cmd/git_clone.go
completers/jj_completer/cmd/root.go

jj: git clone

---

pkg/actions/env/jj.go

jj: environment variables

---

pkg/actions/tools/jj/commit.go
pkg/actions/tools/jj/rev.go

jj: head commits

---

pkg/actions/tools/jj/diff.go

jj: revision changes

---

completers/jj_completer/cmd/branch_create.go
completers/jj_completer/cmd/branch_delete.go
completers/jj_completer/cmd/branch_forget.go
completers/jj_completer/cmd/branch_list.go
completers/jj_completer/cmd/branch_set.go
completers/jj_completer/cmd/branch_track.go
completers/jj_completer/cmd/branch_untrack.go

jj: branch

---

completers/jj_completer/cmd/checkout.go

jj: checkout

---

completers/jj_completer/cmd/commit.go

jj: commit

---

completers/jj_completer/cmd/merge.go
completers/jj_completer/cmd/move.go

jj: merge and move

---

completers/jj_completer/cmd/rebase.go

jj: rebase

---

completers/jj_completer/cmd/describe.go
completers/jj_completer/cmd/diff.go

jj: describe and diff

---

completers/jj_completer/cmd/abandon.go
completers/jj_completer/cmd/backout.go

jj: abandon and backout

---

completers/jj_completer/cmd/restore.go

jj: restore

---

completers/jj_completer/cmd/squash.go

jj: squash

---

completers/jj_completer/cmd/git_remote_add.go
completers/jj_completer/cmd/git_remote_remove.go
completers/jj_completer/cmd/git_remote_rename.go
pkg/actions/tools/jj/remote.go

jj: remote

---

completers/jj_completer/cmd/diffedit.go

jj: diffedit

---

completers/jj_completer/cmd/duplicate.go
completers/jj_completer/cmd/edit.go

jj: duplicate and edit

---

completers/jj_completer/cmd/git_fetch.go
pkg/actions/tools/jj/branch.go

jj: git fetch

---

completers/jj_completer/cmd/operation_restore.go
completers/jj_completer/cmd/operation_undo.go
pkg/actions/tools/jj/operation.go

jj: operation

---

completers/jj_completer/cmd/obslog.go

jj: obslog

---

completers/jj_completer/cmd/git_push.go

jj: git push

---

completers/jj_completer/cmd/unsquash.go
completers/jj_completer/cmd/untrack.go

jj: unsquash and untrack

---

completers/jj_completer/cmd/workspace_add.go
completers/jj_completer/cmd/workspace_forget.go
pkg/actions/tools/jj/workspace.go

jj: workspace add and forget

---

completers/jj_completer/cmd/config_get.go
completers/jj_completer/cmd/config_list.go
completers/jj_completer/cmd/config_set.go
pkg/actions/tools/jj/config.go

jj: config

---

completers/jj_completer/cmd/interdiff.go

jj: interdiff

---

completers/jj_completer/cmd/branch_list.go
completers/jj_completer/cmd/git_push.go
completers/jj_completer/cmd/log.go
pkg/actions/tools/jj/rev.go

jj: revsets

---

completers/git_completer/cmd/commitGraph.go
completers/git_completer/cmd/commitGraph_verify.go
completers/git_completer/cmd/commitGraph_write.go

git: commit-graph

---

completers/ffmpeg_completer/cmd/root.go

ffmpeg: added missing filter_complex flag

---

completers/ffmpeg_completer/cmd/root.go
pkg/actions/tools/ffmpeg/codec.go
pkg/actions/tools/ffmpeg/decoder.go
pkg/actions/tools/ffmpeg/demuxer.go
pkg/actions/tools/ffmpeg/encoder.go
pkg/actions/tools/ffmpeg/filter.go
pkg/actions/tools/ffmpeg/muxer.go
pkg/actions/tools/ffmpeg/protocol.go

ffmpeg: restructure command

---

completers/ffmpeg_completer/cmd/root.go

ffmpeg: bitrate

---

completers/ffmpeg_completer/cmd/root.go

ffmpeg: more flags

---

completers/git_completer/cmd/merge.go

git: merge - limit to branches and tags

---

completers/bat_completer/cmd/root.go

Add aliases for paging to bat completer

---

completers/gh_completer/cmd/auth_login.go
completers/gh_completer/cmd/auth_logout.go
completers/gh_completer/cmd/auth_switch.go
completers/gh_completer/cmd/auth_token.go
completers/gh_completer/cmd/codespace_create.go
completers/gh_completer/cmd/repo_sync.go
completers/gh_completer/cmd/run_list.go
completers/gh_completer/cmd/workflow_run.go
pkg/actions/tools/gh/config.go
pkg/actions/tools/gh/graphql.go

related https://github.com/cli/cli/issues/326

gh: updates from 2.40.0

---

completers/git_completer/cmd/status.go

git: status -- added dash completion

---

completers/git_completer/cmd/log.go

git: log -- added dash completion

---

completers/git_completer/cmd/diff.go
pkg/actions/tools/git/change.go
pkg/actions/tools/git/diff.go

git: diff - only complete changed files

---

pkg/actions/tools/git/change.go

git: ActionChanges - support `./` path prefix

---

completers/git_completer/cmd/add.go

git: add - dash completion

---

completers/git_completer/cmd/blame.go
completers/git_completer/cmd/gui_blame.go
completers/git_completer/cmd/log.go
completers/git_completer/cmd/shortlog.go
completers/git_completer/cmd/whatchanged.go
pkg/actions/tools/git/ls.go

git: integrate file completion

---

completers/clamdtop_completer/cmd/root.go

clamdtop: integrate file completion

---

completers/docker_completer/cmd/container_cp.go

docker: integrate file completion

---

completers/docker-compose_completer/cmd/cp.go

docker-compose: integrate file completion

---

completers/code_completer/cmd/root.go

code: integrate file completion

---

completers/cargo_completer/cmd/action/package.go
completers/cargo_completer/cmd/add.go

cargo: integrate file completion

---

completers/tig_completer/cmd/root.go

tig: integrate file completion

---

completers/go_completer/cmd/mod_edit.go
completers/go_completer/cmd/work_edit.go

go: integrate file completion

---

completers/yarn_completer/cmd/plugin_import.go

yarn: integrate file completion

---

completers/tinygo_completer/cmd/root.go
pkg/actions/tools/tinygo/target.go

tinygo: integrate file completion

---

completers/rsync_completer/cmd/action/format.go
completers/rsync_completer/cmd/root.go
pkg/actions/tools/rsync/debug.go
pkg/actions/tools/rsync/format.go

rsync: integrate file completion

---

completers/go-tool-doc_completer/cmd/root.go

go-tool-doc: integrate file completion

---

completers/helm_completer/cmd/get_all.go
completers/helm_completer/cmd/get_hooks.go
completers/helm_completer/cmd/get_manifest.go
completers/helm_completer/cmd/get_notes.go
completers/helm_completer/cmd/get_values.go
completers/helm_completer/cmd/history.go
completers/helm_completer/cmd/install.go
completers/helm_completer/cmd/plugin_uninstall.go
completers/helm_completer/cmd/plugin_update.go
completers/helm_completer/cmd/pull.go
completers/helm_completer/cmd/repo_remove.go
completers/helm_completer/cmd/rollback.go
completers/helm_completer/cmd/show_all.go
completers/helm_completer/cmd/show_chart.go
completers/helm_completer/cmd/show_readme.go
completers/helm_completer/cmd/show_values.go
completers/helm_completer/cmd/status.go
completers/helm_completer/cmd/test.go
completers/helm_completer/cmd/uninstall.go
completers/helm_completer/cmd/upgrade.go
pkg/actions/tools/helm/plugin.go
pkg/actions/tools/helm/release.go
pkg/actions/tools/helm/repo.go
pkg/actions/tools/helm/revision.go

helm: integrate file completion

---

completers/minikube_completer/cmd/image_load.go
completers/minikube_completer/cmd/start.go

minikube: integrate file completion

---

completers/npm_completer/cmd/action/action.go
completers/npm_completer/cmd/cache_add.go
completers/npm_completer/cmd/diff.go
completers/npm_completer/cmd/edit.go
completers/npm_completer/cmd/install.go
completers/npm_completer/cmd/installTest.go
completers/npm_completer/cmd/link.go
completers/npm_completer/cmd/prune.go
completers/npm_completer/cmd/root.go
completers/npm_completer/cmd/runScript.go
completers/npm_completer/cmd/setScript.go
completers/npm_completer/cmd/uninstall.go
completers/npm_completer/cmd/update.go
pkg/actions/tools/npm/config.go
pkg/actions/tools/npm/module.go
pkg/actions/tools/npm/owner.go
pkg/actions/tools/npm/package.go
pkg/actions/tools/npm/script.go
pkg/actions/tools/npm/workspace.go

npm: integrate file completion

---

completers/pamac_completer/cmd/install.go

pamac: integrate file completion

---

completers/pandoc_completer/cmd/root.go
pkg/actions/tools/pandoc/format.go
pkg/actions/tools/pandoc/format_test.go

pandoc: integrate file completion

---

completers/pip_completer/cmd/install.go

pip: integrate file completion

---

completers/pnpm_completer/cmd/add.go

pnpm: integrate file completion

---

completers/restic_completer/cmd/action/host.go

restic: integrate file completion

---

completers/vercel_completer/cmd/root.go

vercel: integrate file completion

---

completers/gh_completer/cmd/codespace_cp.go

gh: integrate file completion

---

completers/kubectl_completer/cmd/cp.go

kubectl: integrate file completion

---

pkg/actions/tools/syft/source.go

syft: integrate file completion

---

completers/git_completer/cmd/am.go

git: am - dash completion

---

completers/git_completer/cmd/apply.go

git: apply - dash completion

---

completers/git_completer/cmd/bisect_start.go

git: bisect start - dash completion

---

completers/git_completer/cmd/branch.go

git: branch - dash completion

---

README.md
completers/git_completer/cmd/stash.go
completers/git_completer/cmd/stash_push.go

git: stash - dash completion

---

completers/git_completer/cmd/switch.go

git: switch - dash completion

---

docs/src/spec/bridge.md
go.mod
go.sum

- elvish: tag support
- doc: added missing header

doc: added missing header

---

go.mod
go.sum

elvish: tag support

---

completers/git_completer/cmd/commit.go

git: commit - added --no-* flags

---

completers/kubectl_completer/cmd/annotate.go
completers/kubectl_completer/cmd/attach.go
completers/kubectl_completer/cmd/autoscale.go
completers/kubectl_completer/cmd/clusterInfo_dump.go
completers/kubectl_completer/cmd/cordon.go
completers/kubectl_completer/cmd/cp.go
completers/kubectl_completer/cmd/create_clusterrolebinding.go
completers/kubectl_completer/cmd/create_job.go
completers/kubectl_completer/cmd/create_rolebinding.go
completers/kubectl_completer/cmd/delete.go
completers/kubectl_completer/cmd/describe.go
completers/kubectl_completer/cmd/drain.go
completers/kubectl_completer/cmd/exec.go
completers/kubectl_completer/cmd/expose.go
completers/kubectl_completer/cmd/get.go
completers/kubectl_completer/cmd/label.go
completers/kubectl_completer/cmd/logs.go
completers/kubectl_completer/cmd/patch.go
completers/kubectl_completer/cmd/root.go
completers/kubectl_completer/cmd/scale.go
completers/kubectl_completer/cmd/set_image.go
completers/kubectl_completer/cmd/set_resources.go
completers/kubectl_completer/cmd/set_serviceaccount.go
completers/kubectl_completer/cmd/set_subject.go
completers/kubectl_completer/cmd/taint.go
completers/kubectl_completer/cmd/top_node.go
completers/kubectl_completer/cmd/top_pod.go
completers/kubectl_completer/cmd/uncordon.go

kubectl: honor namespace flag in completions

---

cmd/carapace/cmd/invoke.go
go.mod
go.sum

bridges: check if command is known

---

completers/git-clang-format_completer/cmd/root.go
completers/git_completer/cmd/root.go
pkg/actions/tools/git/alias.go

git: aliases - fix type in git-dir

---

completers/git_completer/cmd/blame.go
pkg/actions/tools/git/config.go

git: alias - support external commands

---

completers/git_completer/cmd/maintenance.go
completers/git_completer/cmd/maintenance_register.go
completers/git_completer/cmd/maintenance_run.go
completers/git_completer/cmd/maintenance_start.go
completers/git_completer/cmd/maintenance_stop.go
completers/git_completer/cmd/maintenance_unregister.go
pkg/actions/tools/git/maintenance.go

git: added maintenance

---

completers/git_completer/cmd/switch.go
pkg/actions/tools/git/branch.go

git: switch - list remote branch names

---

completers/git_completer/cmd/add.go

git: add - stage alias

---

completers/brew_completer/cmd/analytics.go

brew: analytics

---

pkg/actions/tools/git/alias.go

git: alias - fix out of range error

---

cmd/carapace/cmd/root.go

shim: log error message

---

completers/code_completer/cmd/action/extension.go
completers/gradle_completer/cmd/root.go
completers/pulumi_completer/cmd/action/urn.go
completers/sdkmanager_completer/cmd/action/action.go
go.mod
go.sum
pkg/actions/fs/tar.go
pkg/actions/tools/dbt/resource.go
pkg/actions/tools/gh/gh.go
pkg/actions/tools/mvn/project.go
pkg/actions/tools/youtubedl/youtubedl.go

updated carapace

---

completers/helm_completer/cmd/action/release.go
completers/helm_completer/cmd/get_all.go
completers/helm_completer/cmd/get_hooks.go
completers/helm_completer/cmd/get_manifest.go
completers/helm_completer/cmd/get_notes.go
completers/helm_completer/cmd/get_values.go
completers/helm_completer/cmd/history.go
completers/helm_completer/cmd/rollback.go
completers/helm_completer/cmd/status.go
completers/helm_completer/cmd/test.go
completers/helm_completer/cmd/uninstall.go
completers/helm_completer/cmd/upgrade.go

helm: extracted local ActionReleases

---

completers/git_completer/cmd/commit.go
pkg/actions/tools/gh/owner.go

git: commit - added missing flags

---

completers/git-browse_completer/cmd/root.go
completers/git-browse_completer/main.go

added git-browse

---

completers/gh_completer/cmd/action/action.go
completers/gh_completer/cmd/action/artifacts.go
completers/gh_completer/cmd/action/cache.go
completers/gh_completer/cmd/action/content.go
completers/gh_completer/cmd/action/environment.go
completers/gh_completer/cmd/action/issue.go
completers/gh_completer/cmd/action/job.go
completers/gh_completer/cmd/action/key.go
completers/gh_completer/cmd/action/label.go
completers/gh_completer/cmd/action/pullrequest.go
completers/gh_completer/cmd/action/ruleset.go
completers/gh_completer/cmd/action/run.go
completers/gh_completer/cmd/action/team.go
completers/gh_completer/cmd/action/template.go
completers/gh_completer/cmd/action/topic.go
completers/gh_completer/cmd/action/variable.go
completers/gh_completer/cmd/action/workflow.go
completers/gh_completer/cmd/api.go
pkg/actions/env/gh.go
pkg/actions/tools/gh/api.go
pkg/actions/tools/gh/graphql.go

gh: enterprise - support custom host

---

completers/tealdeer_completer/cmd/root.go
completers/tealdeer_completer/main.go
completers/tldr_completer/cmd/root.go
pkg/actions/tools/tldr/command.go

Closes https://github.com/carapace-sh/carapace-bin/issues/2342
EDIT: rebased against https://github.com/carapace-sh/carapace-bin/pull/2345

Added completer for tealdeer tldr client

---

pkg/actions/tools/git/ref.go

git: ActionRefs - basic support for dates

---

completers/git_completer/cmd/show.go

git: ActionRefs - fix delimiter

---

completers/git_completer/cmd/commit.go
completers/git_completer/cmd/mergeTree.go
completers/git_completer/cmd/push.go
completers/git_completer/cmd/tag.go
pkg/actions/tools/git/ref.go

git: ActionRefs - use boolean for HeadCommits

---

completers/jj_completer/cmd/parallelize.go

jj: added parallelize

---

pkg/actions/tools/jj/branch.go

jj: fix ActionRemoteBranches

---

completers/make_completer/cmd/root.go

make: fix directory change

---

.github/workflows/go.yml
.goreleaser.yml

fix #2362 
needs https://github.com/goreleaser/goreleaser/pull/4810

goreleaser: fix termux

---

pkg/actions/tools/git/commit.go
pkg/actions/tools/git/ref.go

git: ActionRefs - use ActionHeadCommits

---

README.md

readme: updated getting started

---

docs/src/install.md

doc: add zypper install

---

docs/src/install.md

This reverts commit f30fcc40bc21601fc10bc8abc9175723c3ea0d78, reversing
changes made to ea71b7c3299425a2ad490fa9a6286e24a7d141f5.

Revert "Merge pull request #2398 from carapace-sh/doc-termux-update"

---

cmd/carapace/cmd/lazyinit/xonsh.go

related carapace-sh/carapace#1024

xonsh: fix empty result

---

completers/sudo_completer/cmd/root.go

sudo: complete files

---

completers/git_completer/cmd/common/diff.go
completers/git_completer/cmd/diffFiles.go
completers/git_completer/cmd/log.go

git: fix relative flag

---

completers/git_completer/cmd/root.go
go.mod
go.sum

git: expand `git-dir` and `work-tree`

---

completers/git_completer/cmd/unpackFile.go

git: unpack-file

---

completers/git_completer/cmd/prunePacked.go

git: prune-packed

---

completers/git_completer/cmd/getTarCommitId.go

git: get-tar-commit-id

---

completers/git_completer/cmd/version.go

git: version

---

completers/git_completer/cmd/shell.go

git: shell

---

completers/git_completer/cmd/diffTree.go

git: diff-tree

---

completers/git_completer/cmd/diagnose.go

git: diagnose

---

completers/git_completer/cmd/replay.go

git: replay

---

completers/ffmpeg_completer/cmd/root.go
pkg/actions/tools/ffmpeg/codec.go

This makes the completer aware if it should list the decoders or encoders when selecting completing a codec, not sure if this was done in the cleanest way?

ffmpeg position aware codec selection

---

completers/git-browse-ci_completer/cmd/root.go
completers/git-browse-ci_completer/main.go

added git-browse-ci

---

completers/git-clear_completer/cmd/root.go
completers/git-clear_completer/main.go

added git-clear

---

completers/git-clear-soft_completer/cmd/root.go
completers/git-clear-soft_completer/main.go

added git-clear-soft

---

completers/git-coauthor_completer/cmd/root.go
completers/git-coauthor_completer/main.go
pkg/actions/tools/gh/email.go

added git-coauthor

---

pkg/actions/tools/git/ref.go

git: ActionRefRanges - no need for invoke

---

pkg/actions/tools/git/change.go

git: ActionChanges - small refactor

---

docs/src/bridges.md
docs/src/spec/bridge.md

doc: add notice about clap-rs/clap#3166

---

docs/src/install.md

docs: updated homebrew instructions

---

cmd/carapace/cmd/lazyinit/powershell.go

powershell: support `exe` extension

---

cmd/carapace/cmd/lazyinit/powershell.go

powershell: register with list

---

completers/eza_completer/cmd/root.go

eza: updates from v0.19.3

---

completers/fd_completer/cmd/root.go

Added new flags taken from running `fd --help`

Updated `fd` completions

---

completers/yt-dlp_completer/cmd/root.go

Fix output path completion

---

completers/eza_completer/cmd/root.go

eza: fix time-style

---

pkg/actions/color/256.go
pkg/actions/color/ansi.go
pkg/actions/color/hex.go

Fix color names

---

cmd/carapace/cmd/lazyinit/powershell.go

powershell: fix trimend

---

cmd/carapace/cmd/lazyinit/powershell.go

powershell: fix replace

---

cmd/carapace/cmd/lazyinit/elvish.go
go.mod
go.sum

elvish: register `.exe` completion on windows

---

cmd/carapace/cmd/lazyinit/nushell.go

nushell: support `.exe` completion on windows

---

.docker/fzf-tab.yaml
.docker/fzf-tab/.zshrc
.docker/fzf-tab/Dockerfile
compose.yaml

compose: added fzf-tab

---

.docker/apk.yaml
.docker/apk/Dockerfile
cmd/carapace/cmd/invoke.go
compose.yaml
go.mod
go.sum

compose: added apk

---

.docker/xbps.yaml
.docker/xbps/Dockerfile
compose.yaml

compose: added xbps

---

.docker/cmd-clink.yaml
.docker/cmd-clink/Dockerfile
compose.yaml

compose: added cmd-clink

---

cmd/carapace/cmd/lazyinit/fish.go
docs/src/release_notes/v1.x.md
docs/src/setup.md
go.mod
go.sum

fish: erase existing for tombstone

---

README.md
docs/src/carapace-bin.md

Oilshell has moved, update the links.

Update URL to oilshell.

---

completers/git_completer/cmd/archimport.go
completers/git_completer/cmd/archive.go
completers/git_completer/cmd/bisect_bad.go
completers/git_completer/cmd/bisect_good.go
completers/git_completer/cmd/bisect_run.go
completers/git_completer/cmd/bisect_skip.go
completers/git_completer/cmd/bisect_terms.go
completers/git_completer/cmd/bisect_visualize.go

git: bisect dash completion

---

completers/git_completer/cmd/bundle_create.go
completers/git_completer/cmd/bundle_verify.go

git: bundle dash completion

---

completers/git_completer/cmd/catFile.go
completers/git_completer/cmd/checkIgnore.go
completers/git_completer/cmd/checkoutIndex.go
completers/git_completer/cmd/cherry.go
completers/git_completer/cmd/cherryPick.go

git: more dash completion

---

completers/git_completer/cmd/reflog_show.go
pkg/actions/time/time.go
pkg/actions/tools/git/ref.go
pkg/actions/tools/git/reflog.go

git: reflog completion

---

completers/jj_completer/cmd/bookmark_forget.go
completers/jj_completer/cmd/sign.go
completers/jj_completer/cmd/unsign.go
pkg/actions/net/ssh/key.go
pkg/actions/tools/jj/signing.go

- Added `--include-remotes` flag to `jj bookmark forget`
- Added `jj sign/unsign` commands

jj_completer: updated to jujutsu 0.27.0

---

completers/nix_completer/cmd/build.go

nix: build - complete file attributes

---

completers/pacman_completer/cmd/database.go
completers/pacman_completer/cmd/deptest.go
completers/pacman_completer/cmd/files.go
completers/pacman_completer/cmd/query.go
completers/pacman_completer/cmd/remove.go
completers/pacman_completer/cmd/sync.go
completers/pacman_completer/cmd/upgrade.go

pacman: simply complete files to query file database

---

completers/yay_completer/cmd/files.go

yay: simply complete files to query file database

---

completers/journalctl_completer/cmd/root.go

journalctl: complete units

---

pkg/actions/tools/nix/installables.go

nix: ActionInstallables - support local attributes

---

completers/journalctl_completer/cmd/root.go
completers/systemctl_completer/cmd/action/action.go
pkg/actions/tools/systemctl/unit.go

systemctl: complete inactive units

---

completers/git_completer/cmd/cherryPick.go
completers/git_completer/cmd/commit.go
completers/git_completer/cmd/merge.go
completers/git_completer/cmd/pull.go
completers/git_completer/cmd/rebase.go
completers/git_completer/cmd/revert.go
completers/git_completer/cmd/tag.go
pkg/actions/tools/git/cleanup.go
pkg/actions/tools/git/config.go
pkg/actions/tools/git/merge.go

git: pull - use common actions

---

completers/skhd_completer/cmd/root.go
completers/skhd_completer/main.go

https://github.com/koekeishiya/skhd
Completion flags are from https://github.com/koekeishiya/skhd#usage

Add `skhd` completer

---

completers/common/git_completer/cmd/root.go

git: alias - complete shell commands

---

.docker/issue-2781.yaml
.docker/issue-2781/50_shell.fish
.docker/issue-2781/Dockerfile
compose.yaml
go.mod
go.sum

fish: fix infinite recursion

---

completers/common/git-utimes_completer/cmd/root.go
completers/common/git-utimes_completer/main.go

added git-utimes

---

completers/common/jj_completer/cmd/bookmark.go

jj: add bookmark "b" alias

---

pkg/actions/tools/systemctl/unit.go

systemctl: added `ActionUnitFiles`

---

completers/common/systemctl_completer/cmd/status.go

systemctl: status - use ActionUnitFiles

---

completers/common/nix_completer/cmd/eval.go

fix: nix eval args are flake refs

---

completers/common/gh_completer/cmd/action/action.go

gh: repoOverride - added warning for missing default repository

---

completers/common/kitty_completer/cmd/root.go
completers/common/kitty_completer/main.go

added kitty

---

completers/common/kitty_completer/cmd/root.go

kitty: fix partial directory completion

---

completers/common/kitten_completer/cmd/root.go
completers/common/kitten_completer/main.go
go.mod
go.sum

added kitten

---

completers/common/chmod_completer/cmd/root.go
go.mod
go.sum

fix #2964
needs https://github.com/carapace-sh/carapace/pull/1156

chmod: support implicit (a)ll
